# Generated by Django 5.0 on 2023-12-06 22:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, unique=True)),
                ("description", models.TextField(max_length=120)),
                (
                    "quantity",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(
                                0, message="Quantity must be greater than or equal to 0"
                            ),
                            django.core.validators.MaxValueValidator(
                                100,
                                message="Quantity must be less than or equal to 100",
                            ),
                        ]
                    ),
                ),
            ],
        ),
    ]
